### ISSUE TITLE
Doesn't work on LTSB 1607

### ISSUE THREAD

**Issue by arukateru** [namazso/SecureUxTheme#123]
On LTSB 1607 applying the theme does not change anything. It says installed: yes loaded: no after installation

**Comment by toiletflusher** [comment]
I have the same issue.
![image](https://user-images.githubusercontent.com/80153347/198020392-03359022-6ea9-47bb-8dab-7f77f1cd88a2.png)

**Comment by kusalux** [comment]
Just to be curious, did you test [dev vers](https://github.com/namazso/SecureUxTheme/actions) too? I'm on 1809 Ent, I am not sure when exactly I did switch but iirc there was a problem too and switching did help. So yeah, I think It was a change due to updates. Note: when using the Jan/Feb version you might have to delete some reg. entries, check: https://github.com/namazso/SecureUxTheme/issues/136
