### ISSUE TITLE
Question - How to stop Kasperskay from rolling back the changes

### ISSUE THREAD

**Issue by FlyingBackdoor** [namazso/SecureUxTheme#24]
File is undetected until I apply theme.
As soon as I apply and patched the theme Kaspersky started to roll back everything also deleted the setup file even after adding it to exclusion. 
![image](https://user-images.githubusercontent.com/31269655/89169034-53c09a80-d59b-11ea-8785-ab59e04274ba.png)

**Comment by namazso** [comment]
I have no idea.
Just installed this russian malware into my VM, and besides making everything twice as slow absolutely nothing happened when installing / using SecureUxTheme, even when explicitly running a scan. Maybe they analyzed and whitelisted it since?
![image](https://user-images.githubusercontent.com/8676443/89185904-4acfc900-d59b-11ea-9080-52f8db921794.png)

**Comment by FlyingBackdoor** [comment]
Yes, they've updated their DB. It is working fine now.
