### ISSUE TITLE
Hooking explorer.exe causes it to die

### ISSUE THREAD

**Issue by RaXorX** [namazso/SecureUxTheme#28]
OS: Windows 10 1909 b18363.592 x64

Hooking explorer.exe causes black screen, while the logon is successful. I can see the cursor on the screen, could call task manager and fix it via going to regedit or uninstalling it directly while running the program. (Could call it through task manager)
Explorer seems to be dead at that point, I couldn't call it up manually either. Once uninstalling or going through the regedit fix explorer works fine.

If I don't hook the explorer it seems to be running fine, but my windows Settings app is dead at that point. It gives some error about not being there or something. So, my options are sleek at this point, can't work on windows 10 with the settings app dead. If I hook explorer, it's dead too.

EDIT: Having issues on 1809 b17763.107 x64 (LTSC 2019)
Hooks fine, but I can't apply any theme from the Personalize (Settings UWP Personalize) at all. It just force closes. I can use the app for other settings, cursors/colors etc work fine, but when I click on apply theme it just force closes.

P.S. are the 3rd and 4th option needed to be checked together or only one can be activated at the same time? If I seem to understand correct, they are to avoid the color reverting issue after a logon back from hibernation/sleep/lock.

**Comment by namazso** [comment]
I somehow missed this issue.
Hooking explorer isn't really suggested. That's why it got an exclamation mark now, it tend to cause poor performance, due to the heap debugging we accidentally enable with the debug flag. the Settings app is served by SystemSettings.exe (which has appropriate hook option) and is completely unrelated to explorer hook. Best is to not use any of the unnecessary hooks and just use ThemeTool to set themes.

As for the PS: only one of the options for color reset are needed (or zero if themes you use use default colors, which is a majority of white themes).

Anyways, I might check back to this later on an LTSC vm, but it isn't really priority.

**Comment by RaXorX** [comment]
Sure, no problems. I might have been able to resolve it by reinstalling it again, at least on the desktop. Not sure what was causing it to not work in the VM, even after the reinstalls. Further tests might be needed to run though.

**Comment by namazso** [comment]
This is an almost 2 years old issue, since then I know "CoCreateInstance failed, hr = 80040154" means system is corrupted.
