### ISSUE TITLE
Windows 10 restart screen wrong accent color?

### ISSUE THREAD

**Issue by JDesignEra** [namazso/SecureUxTheme#43]
When restarting the pc, the "Restarting" screen with background color is not changed based on the selected accent colors, it always defaults to the default windows blue background color. But when changing theme with ThemeTool.exe, the "Please Wait" screen shows the correct accent color. Any idea how I could resolved this issue for the restart screen?

This issue was not present when I was using UltraUxThemePatcher previously. And I am on **20H2 (19042.746)** of Windows 10 anyways.

**Comment by namazso** [comment]
Interesting, this sounds more like a problem with ThemeTool than the hook itself. Have you tried enabling "Hook SystemSettings" (then Install) and setting theme through the Settings app?

**Comment by JDesignEra** [comment]
I have just tested it with the **Hook SystemSettings** and setting the theme through the Personalize in Windows Settings and the issue still persist with the restart screen background color.

I just did a double check again and uninstalling ThemeTool and re-installing UltraUxThemePatcher, and the restart background color issue definitely does not exist with UltraUxThemePatcher.

In addition I also tested it without any patchers and there wasn't any issue with the restart background color either.

**Comment by sheeepdev** [comment]
I have a solution, just apply this reg tweak and it will work, tho it may get reset after updates but it didnt happen to me

since i cant upload .reg files here on comments on github you could join my server where i got the tweak from (winthemers)

https://discord.gg/YhddG9JBaQ
https://discord.com/channels/763847972013342740/763855843476766740/800310758645825537
