### ISSUE TITLE
File explorer search box doesn't get themed

### ISSUE THREAD

**Issue by jnki** [namazso/SecureUxTheme#6]
Search box seems to not get themed.
![image](https://user-images.githubusercontent.com/17442109/76711020-fcad4c80-6703-11ea-8bc3-e02af3ba2876.png)
[using the Lace theme in Paranoid Android by niivu](https://www.deviantart.com/niivu/art/Paranoid-Android-Windows-10-Themes-821696974)
Same problem with all the themes in this collection.
Unsure if it's problem with the themes or with SecureUxTheme

Windows 10 Pro x64 1909

**Comment by namazso** [comment]
This isn't a problem with SecureUxTheme, all theme patchers have this. Microsoft changed search bar in 1909 to be UWP, so it no longer uses the current theme.
However I found that this theme comes bundled with a tool that can disable the new searchbar: https://www.deviantart.com/devillnside/art/Simplex-for-Windows-10-1909-1903-824590193
Might want to check that out, it worked on my VM (didn't analyze it further though):
![image](https://user-images.githubusercontent.com/8676443/76997091-f95bd000-6952-11ea-9f94-4c8b5d414588.png)

**Comment by OrthodoxWindows** [comment]
You have to use ExplorerPatcher to solve this bug. https://github.com/valinet/ExplorerPatcher/wiki/All-features

**Comment by rokejulianlockhart** [comment]
@namazso, UWP is an application packaging format. Do you mean XAML?
With XAML Islands becoming more frequently used, especially by Microsoft's stock Windows software, this might become a more prevalent problem.

**Comment by aubymori** [comment]
Hi, just thought I should add on to this:

> Microsoft changed search bar in 1909 to be UWP,

It's actually EdgeHTML, not UWP.

Anyways, there is a better way to get classic search box. You can either update to 19045.3803 (19044.3803 on LTSC) or install Windhawk and the "Legacy Search Bar" mod. The reason you should install the Windhawk mod instead of the other methods is that the Windhawk mod patches a bug where the placeholder text is cleared initially and on a window resize.
