### ISSUE TITLE
Causes many problems on Windows 11

### ISSUE THREAD

**Issue by Kyza** [namazso/SecureUxTheme#60]
Of course, this is obvious especially considering this was tested on a leaked early developer build (21996.1), but I'm posting this here for others and for future reference.

## Known Problems
- Windows persist when hidden to the tray.
- Large lag spikes when maximizing and restoring down some windows.
- Loss of animations such as maximizing, restoring, restoring down, and snapping.

To avoid these problems it's as simple as selecting one of the default themes in Windows.

## What's Working

As far as I can tell applying a theme that was working in the latest stable Windows 10 still changes all the correct colors and assets in Windows 11.

**Comment by namazso** [comment]
As for me: I don't care until an RTM build is out (about a week before general availability).
And these all sound a lot like theme problems, but we'll see

**Comment by enoversum** [comment]
@Kyza This occurred to Insiders already months ago (on their Dev channel, something like an alpha version of Windows) when they obviously introduced some new animations which cause UWP apps and system settings windows to interact weirdly in the way you describe. I had filed an issue here: https://github.com/namazso/SecureUxTheme/issues/42, and it seems that themes need to be modified (by the makers). 
A workaround of the not-so-swift kind is disabling animations (just search for 'animations' in the start menu) until the theme makers have changed their themes. Working since quite a few months now :) .

**Comment by WhiteNervosa** [comment]
> @Kyza This occurred to Insiders already months ago (on their Dev channel, something like an alpha version of Windows) when they obviously introduced some new animations which cause UWP apps and system settings windows to interact weirdly in the way you describe. I had filed an issue here: #42, and it seems that themes need to be modified (by the makers).
> A workaround of the not-so-swift kind is disabling animations (just search for 'animations' in the start menu) until the theme makers have changed their themes. Working since quite a few months now :) .

To add to this; you can leave animations enabled and specifically disabling `Animate windows when minimizing and maximizing` allows for most animations to be kept without explorer crashing every time a window is maximized or snapped. 
`Windows Key+R`, `SystemPropertiesAdvanced`, `Advanced` Tab, Under `Performance` click `Settings...` and then you'll see that option to toggle.

It may vary depending on the theme and no idea what animations this includes because it seems to include more than just those but most seem to be fine ¯\_(ツ)_/¯

**Comment by enoversum** [comment]
For anyone reading here – [niivu](https://www.deviantart.com/niivu) has released/updated his first Windows-11 ready themes that also work with min/max animations. So we're getting closer to smooth Windows 11 themes once again.

**Comment by namazso** [comment]
BIB3 by niivu works properly on most recent Windows 11 builds, none of the issues mentioned are present. Closing so this issue doesn't confuse newcomers. Will do a last check whenever RTM is out

**Comment by enoversum** [comment]
@namazso Can confirm that BIB3 is working flawlessly now.
