### ISSUE TITLE
Renaming CurrentColors

### ISSUE THREAD

**Issue by niss1m** [namazso/SecureUxTheme#74]
![image](https://user-images.githubusercontent.com/45534081/131995536-c9cfcec2-659c-4697-8da6-4a0fd8c44f87.png)

also task manager looks bugged

![image](https://user-images.githubusercontent.com/45534081/131995644-e0127d26-1c38-4d9a-8649-c8e3d8a5d5eb.png)

**Comment by niss1m** [comment]
I get this when trying to install (yes running as admin)

**Comment by namazso** [comment]
someone messed up the ACLs on `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\DefaultColors". you can just do either of these:
- simply delete it
- fix acls
- use logonui hook instead

**Comment by niss1m** [comment]
error is gone tskmngr is still broken though

**Comment by namazso** [comment]
how is it broken? are you applying a dark theme and after locking the colors reset?

**Comment by niss1m** [comment]
well im applying bib 2.0 and tskmngr is still white.

**Comment by namazso** [comment]
Theme issue (or probably rather intentional). You can find reports of default dialog background color not being changed on DeviantArt too.

BIB 2:

![image](https://user-images.githubusercontent.com/8676443/132098520-19c7f4b1-5aae-437e-9a24-93790e5c28d3.png)

Dark by Kdr3w:

![image](https://user-images.githubusercontent.com/8676443/132098605-2be3ae6c-d75a-44b8-b65d-557c83514bb6.png)
