### ISSUE TITLE
CoCreateinstance failed, hr = 80040154

### ISSUE THREAD

**Issue by rymndv** [namazso/SecureUxTheme#79]
![image](https://user-images.githubusercontent.com/73246824/135923511-1f56d225-cdad-4ae6-94ed-7e921fcb349d.png)
Getting this error when launching to install

**Comment by namazso** [comment]
Probably corrupted system. Post exact version number from `winver`. Also try `sfc /scannow` to fix corruptions if any.

**Comment by yunafires** [comment]
I'm getting this issue as well. 
winver = windows 11, Version 21h2 (os build 22000.318)
I have no idea what sfc/scannow is.

**Comment by namazso** [comment]
@yunafires https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e

since then i had some reports about this, the common pattern i see is watching some idiot's video on youtube that replaces these dlls with outdated and incompatible versions, so case solved. I don't support broken / corrupted windows installs.
